### PR TITLE
cosmetic changes

### PR DESCRIPTION
**Pull request by vojtatranta**
What do those folks Václavík and Rys teach you about Promises? :-)) Gotta fix it!
I hope it works I tried not to make any change, just fix that cosmetical things like wrapping Promise with another Promise, it makes no sense. It seems that you don't understand true beauty and nature of Promises, read on:
https://medium.com/@vojta/from-callback-hell-to-promise-hell-c922bf2d5efb#.6huqkwhh2

### CODE REVIEW

**Comment by Nodonisko** [comment]
I have not so much experience with promises (i love observables :D), so thank u for your post a commit, it's really helpful and interesting ;)

**Comment by vojtatranta** [comment]
Observables and promises are practically same thing. Both implement `flatMap` so it can be consumed. Both behave ~ like ~ monad.

**Comment by vojtatranta** [comment]
Have you tested my MR before you merged it? Should have!

**Comment by Nodonisko** [comment]
Testing right now, i was so fast with clicking merge button :)

**Comment by Nodonisko** [comment]
Everything is tested and fixed :+1: It looks more sexy now, thank :)

**Pull request merged**
