### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by ihadeed**

### CODE REVIEW

**Comment by fabianlaule** [comment]
@ihadeed Thank you very much for the contribution. Currently, I am developing an app in Ionic 3 as a student project and I found this package. Do you know a possibility to use the current master branch for Ionic 3 before the package is officially released?

**Comment by ihadeed** [comment]
@fabianlaule 

You can use the package `ionic-cache-dev` ... it's just a temporary package I published. I have another package `ionic-cache-is` that uses `IonicStorage` instead of the current approach.

**Comment by fabianlaule** [comment]
@ihadeed Wow, thanks a lot for this information. I've implemented it and it works without any issues so far. 

@Nodonisko thank you for this amazing package and thanks to @ihadeed for the pull requests. It saves me a lot of time!

**Comment by Nodonisko** [comment]
@fabianlaule Thanks :) I will release new version with all changes to NPM today.

**Comment by Nodonisko** [comment]
@fabianlaule @ihadeed v2.0.0 is released now :)

**Pull request merged**
