### PR TITLE
Added AES encryption to cached content

### PR DESCRIPTION
**Pull request by mobile-support93**
Added AES encryption to cached content using crypto.js. Added a function setEncryptionKey() to set the encryption key. If no key is set, content is cached as usual.

### CODE REVIEW

**Comment by Nodonisko** [comment]
@mobile-support93 Thanks for nice feature, could you also provide tests?

**Comment by mobile-support93** [comment]
@Nodonisko Sorry, currently I don't have the bandwidth to write the test cases; I have resolved the conflicts.

**Comment by ramonornela** [comment]
Maybe best add strategy to decode() and encode() ex: https://gist.github.com/ramonornela/2d62439012888904bf713401bb2b7340

**Comment by WillPoulson** [comment]
This would be great functionality to implement however it would also add the dependency for `crypto-js`

**Comment by Nodonisko** [comment]
Thanks for PR, but this need to be reimplement to reflect new structure of project, probably should be placed into own class or inside cache storage class. Another option could be implementing of own observable operator.

Closing this for now, feel free to reopen.

**Pull request closed without merging**
